language: node_js
node_js:
  - node

before_script:
  - npm install -g bower
  - bower install

script: bash ./deploy.sh

env:
  global:
  - ENCRYPTION_LABEL: "a84636109e68"
  - COMMIT_AUTHOR_EMAIL: "njt1982@gmail.com"

cache:
  directories:
    - node_modules # NPM Packages